select campaignname as campaign_name,
        campaignid as campaign_id,
        impressions,
        clicks,
        cost,
        bounces,
        sessions,
        ctr,
        type,
        goal,
        campaignType as campaign_type,
        date,
        registrations as registrations_plan,
        conversioncost as conversion_cost_plan,
        budget,
        widgetcopied as widget_copied,
        direct_regs_count,
        direct_copies_count,
        conversions_count,
        conversion_rate,
        conversion_cost
from `dwh-wazzup`.`widget`.`yandex_direct`